title: Welcome to toyobaba's homepage!
collections:
    projects:
       sort_by: index
    works:
       sort_by: index
    
author: Omotoyosi Taiwo
description: "Small page to display the works I've done"
keywords: "Software Engineering, Electrical Engineering, Programming"
colophon: "This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

github_username: toyobaba
linkedin_username: omotoyosi-taiwo-a201b820
facebook_username: omotoyosi.taiwo 

markdown: kramdown
highlighter: rouge
